### ISSUE TITLE
tradingview-js-api-tutorial Integration

### ISSUE THREAD

**Issue by milesmiles902** [jonchurch/tradingview-js-api-tutorial#4]
Would you be willing to help me out on this?
https://github.com/tradingview/charting_library/issues/3388

**Comment by milesmiles902** [comment]
Jon,

Please help. I'm noob.

_Miles

**Comment by milesmiles902** [comment]
In reality, all the JS should work the same without React and I have an HTTPS server already running on the VPS. Shouldn't I just be able to refer to the correct index.html and npm run build?

I'm noob.

**Comment by jonchurch** [comment]
Hey there, react isnt a webserver. You would run npm build and then host
the resulting bundle and index.html.

Im not sure what your actual issue is, but if you have a question about the
tutorial Im happy to help you.

**Comment by milesmiles902** [comment]
Thanks so much Jon! I am only partial noob now because I will make my question clearer.

If i want to host the resulting /build folder on a web server, such as digital ocean or heroku. I would need to migrate https://github.com/milesmiles902/Build over to the server and reference the index.html with an npm express or serve client, .htaccess etc? I just want to be able to see it within the browser without the local testing environment and am unsure on the process.

**Comment by milesmiles902** [comment]
I'll post a mini-guide when I figure it out.

**Comment by milesmiles902** [comment]
Fixed 
npm run build
Put in server root as mentioned by Jon.

Although, I'm still noob.
